### ISSUE TITLE
Test bug

### ISSUE THREAD

**Issue by leagueoffoundryvttdevs** [AndrewJiangB/hero-creation-tool#65]
**Submitted By**: Iñaki
**Feedback Type**: Bug
 
**Core:** 0.8.8
**System:** dnd5e v1.4.x
**Module Version:** hero-creation-tool v0.0.3
 
**Description**:
I was trying to report a bug!<details>
<summary>Module Settings</summary>

```js
displayNameMode: 50,
displayBarsMode: 30,
classCompendiums: world.mis-clases
```
</details>

**Comment by ccjmk** [comment]
@DJDANNYG you can safely delete this, I was just trying the functionality!
